version: "3.8"

services:
  bot:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ..:/app
    env_file:
      - ./bot.env
    command: ["sh", "-lc", "pip install -r requirements.txt && python -m src.run"]
    restart: unless-stopped

